[package]
name = "windows-projfs"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.20"
thiserror = "1.0.52"
widestring = "1.0.2"
windows = { version = "0.52.0", features = [
    "Win32_Storage_ProjectedFileSystem",
    "Win32_Foundation",
] }
