[package]
name = "example-virtual-fs"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.77"
clap = { version = "4.4.11", features = ["derive"] }
env_logger = "0.10.1"
log = "0.4.20"
windows-projfs = { version = "0.1.0", path = "../../windows-projfs" }
